services:
  host:
    image: ghcr.io/roganik/areyougoingbot:latest
    command: >
      sh -c "dotnet AreYouGoingBot.Storage.Migrations.dll &&
             dotnet AreYouGoingBot.dll"
    env_file: env.conf
    volumes:
      - /root/Docker/are-you-going/AreYouGoing.sqlite:/app/AreYouGoing.sqlite
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"