name: CI

on:
  push:
    branches: [ master, ci-experiments ]
    
  pull_request:
    branches:
      - master

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - 
        name: Output Run Number
        run: echo ${{ github.run_number }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        if: ${{ github.ref == 'refs/heads/master' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build Docker images. (And push if branch == master)
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          file: Dockerfile
          tags: ghcr.io/roganik/areyougoingbot:latest
          build-args: APP_VERSION_SUFFIX=${{ github.run_number }}
